[databases]
swgss-army-knife = host=primary port=5432 dbname=swgss-army-knife

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 5432
auth_type = scram-sha-256
auth_file = /etc/pgbouncer/userlist.txt

pool_mode = transaction
default_pool_size = 5
max_client_conn = 200

max_prepared_statements = 200

;; psql -p 21520 -U app pgbouncer → SHOW POOLS / SHOW CLIENTS / SHOW SERVERS
admin_users = admin,app_user
stats_users = admin,app_user

ignore_startup_parameters = extra_float_digits
